#!/usr/bin/env python
# coding: utf-8

# # Introduction to Quantum Mechanics
# 
# ##  &#x1f3af; Objective
# To review basic aspects of quantum mechanics.
# 
# ## &#x1f4dc; Instructions
# 
# Make sure you fill in any place that says YOUR CODE HERE or "YOUR ANSWER HERE", as well as your name, username (the prefix to your @university.ext e-mail), and student ID number in the cell below

# In[1]:


import numpy as np
import scipy
from scipy import constants


# ## Wave-Particle Duality

# ### &#x1f3b2; Particle-like features of light.
# Which of the following phenomena are strongly associated with the particle-like nature of light. <br>
# **A**. Blackbody radiation <br>
# **B**. Compton Scattering  <br>
# **C**. Electron Diffraction <br>
# **D**. Stern-Gerlach Experiment <br>
# **E**. Photoelectric effect 

# In[2]:


def p1():
    # Report your answer as a list, tuple, or set containing the correct answers. 
    # For example, if the answers are A and C, then ad1 = ["A", "C"]. 
    # I've initialized the answer to the empty list.
    
    ### START YOUR CODE HERE
    ad1 = []
    ### END YOUR CODE HERE
    return ad1

print("The following phenomena are associated with the particle-like nature of light:", p1())


# ### &#x1F5A9; Properties of photons
# What is the frequency of light in Hz ($s^{-1}$) of light with wavelength 500 nm?

# In[3]:


def p2():
    # Use the code box as a calculator, but report your answer as a float. 
    # ansDuality2 = float. I've initialized the answer to None.
    
    ### START YOUR CODE HERE
    ad2 = None
    ### END YOUR CODE HERE
    
    return ad2


# ### &#x1fa99; Properties of photons
# 
# Doubling the wavelength of radiation doubles its frequency. (True/False)

# In[4]:


def p3():
    # Report your answer as a Boolean, so freq_double = True or freq_double = False
    
    ### START YOUR CODE HERE
    freq_double = None
    ### END YOUR CODE HERE
    
    return freq_double


print("It is", p3(), "that when the wavelength of radiation doubles its frequency does also.")


# ### &#x1fa99; Properties of photons
# 
# Doubling the wavelength of radiation halves its speed. (True/False)

# In[5]:


def p4():
    # Report your answer as a Boolean, so speed_halves = True or speed_halves = False
    
    ### START YOUR CODE HERE
    speed_halves = None
    ### END YOUR CODE HERE
    
    return speed_halves


print("It is", p4(), "that when the wavelength of radiation doubles its speed halves.")


# ### &#x1F5A9; Properties of photons
# A helium-neon laser emits light at 632.8 nm.  What is the energy of the photons generated by this laser, in Joules?

# In[6]:


def p5():
    # Use the code box as a calculator, but report your answer as a float. 
    # E_HeNe = float. I've initialized the answer to None.
    
    ### START YOUR CODE HERE
    E_HeNe = None
    ### END YOUR CODE HERE
    
    return E_HeNe


# ### &#x1f3b2; Properties of photons
# 
# Which of the following changes would double the energy of a photon: <br>
# **A**. Doubling its frequency <br>
# **B**. Doubling its wavelength <br>
# **C**. Doubling its momentum <br>
# **D**. Doubling its speed <br>
# **E**. Doubling its effective (relativistic) mass <br>
# **F**. Doubling its wavenumber. 

# In[7]:


def p6():
    # Report your answer as a list, tuple, or set containing the correct answers. 
    # For example, if the answers are A and C, then e_doubles = ["A", "C"]. 
    # I've initialized the answer to the empty list.
    
    ### START YOUR CODE HERE
    e_doubles = []
    ### END YOUR CODE HERE
    
    return e_doubles

print("Ways you can double the energy of a photon include", p6())


# ### &#x1F5A9; Momentum from a green laser pointer
# I have a high-powered green laser pointer (532 nm wavelength, 100 mW power) that I use for astronomical starspotting. If I shine this laser pointer on you, how much momentum, per second, will be transferred to you? Report your answer in SI units of kg m/s.

# In[8]:


def p7():
    # Use the code box as a calculator, but report your answer as a float. 
    # p_greenlaser = float. I've initialized the answer to None.
    
    ### START YOUR CODE HERE
    p_greenlaser = None
    ### END YOUR CODE HERE
    
    return p_greenlaser

print(f"the momentum transfered per second is {p7()} kg m/s")


# ### &#x1F5A9; Wavelength emitted by a radiopharmaceutical
# The radioactive isotope Cobalt-60 is used in nuclear medicine to treat cancer. The energy emitted by Cobalt-60 is 1.29 x 10^11 J/mol. What is the wavelength of the emitted $\gamma$ rays?

# In[9]:


def p8():
    # Use the code box as a calculator, but report your answer as a float. 
    # wlength_Co60 = float. I've initialized the answer to None.
    
    ### START YOUR CODE HERE
    wlength_Co60 = None
    ### END YOUR CODE HERE
    
    return wlength_Co60



# ### &#x1fa99; Davisson-Germer experiment
# The Davisson-Germer experiment was among the first explicit verifications of the wave-like nature of electrons, and was foundational for modern electron diffraction methods. (True/False)

# In[10]:


def p9():   
    # Report your answer as a Boolean, so ad3 = True or ad3 = False
    
    ### START YOUR CODE HERE
    ad3 = None
    ### END YOUR CODE HERE

    return ad3
    
print("The answer is:", p9())


# ### &#x1f3b2; Davisson-Germer experiment
# The Davisson-Germer experiment demonstrated that if you shine a beam of electrons on a metal crystal, the result is <br>
# **A**. the electrons are absorbed at “critical energies” similar to the optical (light) absorption spectrum. <br>
# **B**. the electrons scatter according to the Bragg law for X-ray scattering. <br>
# **C**. the electrons go right through the metal. <br>
# **D**. the metal gets very hot and becomes a dull red color (stimulated blackbody emission of radiation). <br>

# In[11]:


def p10():
    # Report your answer as a list, tuple, or set containing the correct answers. 
    # For example, if the answers are A and C, then ad3b = ["A", "C"]. 
    # I've initialized the answer to the empty list.
    
    ### START YOUR CODE HERE
    ad3b = []
    ### END YOUR CODE HERE

    return ad3b


print("In the Davisson-Germer experiment", p10())


# ### &#x1F5A9; Properties of photons
# What is the momentum of a $\gamma$-ray photon with a wavelength of $10^{-13}$ m in SI units of ${\frac{\text{m} \cdot \text{kg}}{\text{s}}}$?

# In[12]:


def p11():
    # Use the code box as a calculator, but report your answer as a float. 
    # ad4 = float. I've initialized the answer to None.
    
    ### START YOUR CODE HERE
    ad4 = None
    ### END YOUR CODE HERE
    return ad4


# ### &#x1F5A9; Rydberg's Law
# Rydberg's law says that the wavenumber for the absorptions for a one-electron atom/ion with atomic number Z is given by the expression
# $$ \tilde{\nu} = \left( 1.0974 \cdot 10^7 m^{-1}\right) Z^2 
# \left( \frac{1}{n_1^2} - \frac{1}{n_2^2} \right) $$
# where $1 < n_1 < n_2 < \inf$. Suppose you are given the Hydrogen atom in its ground state, $n_1=1$. What is the lowest absorption frequency?

# In[13]:


def p12():
    # Use the code box as a calculator, but report your answer as a float. 
    # ad5 = float. I've initialized the answer to None.
    
    ### START YOUR CODE HERE
    ad5 = None
    ### END YOUR CODE HERE

    return ad5



# ### &#x1f3b2; Wave properties of particles
# Which of the following experimental results are often cited as examples of the wave-likeness of particles like electrons?  
# **A**. blackbody radiation  
# **B**. discrete emission lines in the hydrogen spectrum  
# **C**. photoelectric effect  
# **D**. Compton scattering of light by a particle  
# **E**. Electron scattering from a crystal

# In[14]:


def p13():
    #Report your answer as a list, tuple, or set containing the correct answers. 
    # For example, if the answers are A and C, then ad6 = ["A", "C"]. 
    # I've initialized the answer to the empty list.
    
    ### START YOUR CODE HERE
    ad6 = []
    ### END YOUR CODE HERE
    
    return ad6


print("The following phenomena are associated with the wave-like nature of electrons:", p12())


# ###  &#x1f3b2; Particle properties of waves
# Which of the following experimental results are often cited as examples of the particle-likeness of radiation (light)?   
# **A**. blackbody radiation <br>
# **B**. discrete emission lines in the hydrogen spectrum <br>
# **C**. photoelectric effect <br>
# **D**. Compton scattering of light by a particle <br>
# **E**. Electron scattering from a crystal <br>

# In[15]:


def p14():
    # Report your answer as a list, tuple, or set containing the correct answers. 
    # For example, if the answers are A and C, then ad7 = ["A", "C"]. 
    # I've initialized the answer to the empty list.
    
    ### START YOUR CODE HERE
    ad7 = []
    ### END YOUR CODE HERE
    
    return ad7

print("The following phenomena are associated with the particle-like nature of light:", p13())


# ### &#x1F5A9; Properties of photons
# What is the momentum and energy of a photon with angular wavenumber $k=10^7 \text{m}^{-1}$?

# In[16]:


def p15():
    # Use the code box as a calculator, but report your answer as float(s). 
    # I've initialized the answers to None.
    
    ### START YOUR CODE HERE
    p_from_k = None   #momentum of the photon
    E_from_k = None   #Energy of the photon
    ### END YOUR CODE HERE

    return p_from_k, E_from_k
    
    


# Suppose you are given a photon with an energy of 2 eV. What is its momentum in 
# $\frac{\text{m} \cdot \text{kg}}{\text{s}}$? What is its frequency in Hz?

# In[17]:


def p16():
    # Use the code box as a calculator, but report your answer as float(s). 
    # I've initialized the answers to None.
    
    ### START YOUR CODE HERE
    momentum_d9 = None
    frequency_d9 = None
    ### END YOUR CODE HERE
    
    return momentum_d9, frequency_d9


# ### &#x1F5A9; De Broglie wavelength of a baseball
# During departmental baseball games, your instructor insists that the only reason he strikes out is because of the De Broglie wavelength of the baseball means that even though he swings in the correct location, he still misses. Suppose that the opposing major-league-quality hurler throws the baseball (mass = 145 g) at 100 miles-per-hour (45 m/s). What is the De Broglie wavelength of the baseball?

# In[18]:


def p17():
    # Use the code box as a calculator, but report your answer as float(s). 
    # I've initialized the answer to None.
    
    ### START YOUR CODE HERE
    wl_baseball = None   #wavelength of the baseball.
    ### END YOUR CODE HERE
    
    return wl_baseball



# ## The Schr&ouml;dinger Equation
# 
# ### &#x270d;&#xfe0f; Time-Dependent Schr&ouml;dinger Equation
# What is the time-dependent Schr&ouml;dinger equation for the complex conjugate of the wavefunction, $\Psi^*$?
# Put your answer in the markdown cell below. You can drag and drop an attachment (of most types) to this cell also. 

# ### &#x1f3b2; Hamiltonian operator
# The Hamiltonian operator corresponds to which observable property of a quantum system? <br>
# **A**. Action <br>
# **B**. Momentum <br>
# **C**. Kinetic Energy <br>
# **D**. De Broglie Wavelength <br>
# **E**. Total Energy <br>
# **F**. Angular Momentum <br>
# **G**. Entropy  
# **H**. Planck Mass

# In[19]:


def p18():
    # Report your answer as a list, tuple, or set containing the correct answers. 
    # For example, if the answers are A and C, then ansSE2 = ["A", "C"]. 
    # I've initialized the answer to the empty list.
    
    ### START YOUR CODE HERE
    ansSE2 = []
    ### END YOUR CODE HERE
    
    return ansSE2

print("The Hamiltonian is the quantum-mechanical operator for:", p18())


# ## Mathematics
# ###  &#x1fa99; Mathematical Properties of the wavefunction
# A probability density can never be negative. (True/False)

# In[20]:


def p19():
    # Report your answer as a Boolean, so prob_canbe_negative = True or = False
    
    ### START YOUR CODE HERE
    prob_canbe_negative = None
    ### END YOUR CODE HERE

    return prob_canbe_negative

print("It is", p19(), "that a probability density can be negative.")


# ### &#x1f3b2; Complex Conjugation
# Let $z$ be a complex number. If $w$ is the product of $z$ and its complex 
# conjugate, $w = z z^*$, which of the following is **always** true about $w$: <br>
# **A**. w is an imaginary number. <br>
# **B**. w is a complex number. <br>
# **C**. w is nonzero real number. <br>
# **D**. w is a nonnegative real number. <br>
# **E**. w is a nonzero complex number. <br>
# **F**. None of the above

# In[21]:


def p20():
    # Report your answer as a list, tuple, or set containing the correct answers. 
    # For example, if the answers are A and C, then zzstar = ["A", "C"]. 
    # I've initialized the answer to the empty list.
    
    ### START YOUR CODE HERE
    zzstar = []
    ### END YOUR CODE HERE

    return zzstar

print("The product of a number and its complex conjugate is always", p20())


# ### &#x270d;&#xfe0f; Complex Conjugation
# What is the complex conjugate of 
# $$ \Psi(x,t) = A e^{(a+bi)(kx - \omega t)} $$

# In[ ]:





# ### &#x1fa99; Eigenfunctions of the kinetic-energy operator
# *Every* eigenfunction of the momentum operator is also an eigenfunction of the kinetic-energy operator, and vice versa. (True/False)

# In[22]:


def p21():
    # Report your answer as a Boolean, so is_also_eigenfunction = True or = False
    
    ### START YOUR CODE HERE
    is_also_eigenfunction = True
    ### END YOUR CODE HERE
    
    return is_also_eigenfunction

print("The answer is:", p21())

